openshift/platform-operators

Dockerfile, test/e2e/platform_operators_test.go
Update dockerfile and use the rhel-related base images. Run the build Makefile target in the builder image and copy that PO manager executable into the final image layer.
=> Update the Dockerfile to use downstream images

.golangci.yaml, Makefile, go.sum
Explicitly specify -mod=readonly when installing the tool dependencies
in order to work in downstream CI environments.
These failures were seen in https://github.com/openshift/release/pull/31085.
The other commits were needed in order to get the `make lint` and
`make verify` checks working, so we can reduce the number of PRs
to get CI green.
=> Makefile: Install tool dependencies using -mod=readonly

Makefile
Ensure golangci-lint can successfully run when deployed in the CI
cluster environments by overriding the default cache directory location
to a writable directory (e.g. /tmp).
=> Makefile: Override the golangci-lint cache to a writable directory

Dockerfile, Makefile, config/default/kustomization.yaml, manifests/0000_50_cluster-platform-operator-manager_00-namespace.yaml, manifests/0000_50_cluster-platform-operator-manager_00-platformoperator.crd.yaml, manifests/0000_50_cluster-platform-operator-manager_01-serviceaccount.yaml, manifests/0000_50_cluster-platform-operator-manager_02-metricsservice.yaml, manifests/0000_50_cluster-platform-operator-manager_05_rbac.yaml, manifests/0000_50_cluster-platform-operator-manager_06-deployment.yaml
Adds a root manifests directory which the CVO will use to deploy the PO manager component.
There's some follow-up work once this initial work lands:
- Add the rukpak manifests to the repository
- Add the manifests/image-references file
- Add the downstream rukpak image to the manifests/image-references file
- Add the downstream kube-rbac-proxy to the manfiests/image-references file
- Substitutes the CI built image before running the PO e2e suite
=> Introduce the PO manager CVO manifests

Dockerfile
Temporarily comment out the io.openshift.release.operator Dockerfile label while this repository is still being onboarded to the OCP payload.
=> Dockerfile: Remove the io.openshift.release.operator label

config/default/kustomization.yaml, manifests/0000_60_cluster-platform-operator-manager_00-namespace.yaml, manifests/0000_60_cluster-platform-operator-manager_00-platformoperator.crd.yaml, manifests/0000_60_cluster-platform-operator-manager_00-rukpak-bundledeployments.crd.yaml, manifests/0000_60_cluster-platform-operator-manager_00-rukpak-bundles.crd.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-ca.certificate.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-ca.issuer.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-core-admin.sa.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-core.certificate.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-selfsigned.issuer.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-webhook-selfsigned.issuer.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-webhook.certificate.yaml, manifests/0000_60_cluster-platform-operator-manager_01-rukpak-webhooks-admin.sa.yaml, manifests/0000_60_cluster-platform-operator-manager_01-serviceaccount.yaml, manifests/0000_60_cluster-platform-operator-manager_02-metricsservice.yaml, manifests/0000_60_cluster-platform-operator-manager_02-rukpak-core.service.yaml, manifests/0000_60_cluster-platform-operator-manager_02-rukpak-webhook.service.yaml, manifests/0000_60_cluster-platform-operator-manager_03_rbac.yaml, manifests/0000_60_cluster-platform-operator-manager_04-rukpak-core.deployment.yaml, manifests/0000_60_cluster-platform-operator-manager_04-rukpak-webhooks.deployment.yaml, manifests/0000_60_cluster-platform-operator-manager_05-rukpak.validating-webhook-configuration.yaml, manifests/0000_60_cluster-platform-operator-manager_06-deployment.yaml
The platform operators project is being released as a Tech Preview
feature within OpenShift. A project managed by CVO is designated as a
Tech Preview feature by setting the "release.openshift.io/feature-gate"
annotation to "TechPreviewNoUpgrade". CVO will not apply any resources
with this annotation and key to the cluster unless the cluster has
Tech Preview features enabled.
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
=> Designate Platform Operators as Tech Preview

config/rukpak/apis/webhooks/resources/deployment.yaml, manifests/0000_60_cluster-platform-operator-manager_04-rukpak-webhooks.deployment.yaml
This commit introduces a number of changes aimed at ensuring that the
webhook deployments introduced by the platform operators project remain
highly available during deployment and upgrades.
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
=> Introduce Highly Available Webhook Deployments

config/rukpak/apis/webhooks/kustomization.yml, config/rukpak/apis/webhooks/patches/high-availability.yaml, config/rukpak/apis/webhooks/resources/deployment.yaml
Moves the HA webhook deployment configurations to a patch file to make it easier to toggle this configuration on/off for local crc development usage.
=> config/rukpak: Add the HA webhook configurations to a patch file

Dockerfile
Fails the prodsec static tooling analysis.
=> Dockerfile: Use COPY instead of ADD for copying the manifests directory

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, manifests/0000_50_cluster-platform-operator-manager_06-deployment.yaml
Follow-up to #28 which added the requisite PSA configuration for the rukpak component. This adds that same configuration for the CPOM component.
=> config,manifests: Add PSA configuration for the CPOM deployment

Makefile, manifests/0000_50_cluster-platform-operator-manager_00-platformoperator.crd.yaml
Update the PlatformOperator CRD YAML manifests housed in o/api, and inject the required self-managed HA cluster profile annotation. This is a short term hack in order to unblock payload introduction.
=> Makefile,manifests: Add hack for injecting the self managed HA cluster cluster

config/default/kustomization.yaml, config/rukpak/core/kustomization.yaml, config/rukpak/kustomization.yaml, manifests/0000_50_cluster-platform-operator-manager_04-rukpak-core.deployment.yaml
Moving this out of the WIP #23 PR.
=> config,manifests: Ensure the CPOM and rukpak components use the same kube-rbac-proxy image

Makefile
Adds support for focusing on a single e2e test at a time. Mirrors the setup in the major upstream OLM repositories. Example usage: `make test-e2e TEST="a failing PO has been encountered"`.
=> Makefile: Add support for focusing on a specific test

Makefile, hack/apply-feature-gate.sh
Adds a hack script that's responsible for enabling TP features after cluster creation, and ensuring that the PO components roll out correctly. Note: this was copied from the CAPI component's implementation.
This should be a short term hack as the CI workflows that enable tech preview features before cluster creation are currently permafailing.
=> hack,Makefile: Enable tech preview features after cluster creation

Makefile
Ensure that ginkgo generates a junit report when the $ARTIFACT_DIR environment variable has been specified. This variable is always present when running the testing suite in CI environments.
This was pulled out of the #23 PR which did correctly generate a junit report.
=> Makefile: Ensure a junit report is created when running in CI environments

hack/apply-feature-gate.sh
Update the hack/apply-feature-gate.sh script, and ensure the aggregate platform operators ClusterOperator resource reports an available status.
Moving this out of the #23 PR.
=> hack: Ensure the aggregate CO reports an Available=True condition

api/v1alpha1/types.go, controllers/platformoperator_controller.go, internal/util/util.go, internal/util/util_test.go, test/e2e/aggregated_clusteroperator_test.go, test/e2e/platform_operators_test.go
Follow-up to #44. Renames the TypeApplied status condition type constant variable to TypeInstalled. Moving this change out of the #41 to reduce the unrelated changes to that PR.
=> *: Rename TypeApplied -> TypeInstalled

controllers/aggregated_clusteroperator_controller.go
Moving this out of the #23 PR. This was needed as the aggregate CO was blocking cluster rollout despite reporting an Available=True condition when no POs had been installed.
=> controllers: Set Progressing=False during success states

config/aggregatedclusteroperator/aggregated_clusteroperator.yaml, config/default/kustomization.yaml, manifests/0000_50_cluster-platform-operator-manager_00-namespace.yaml, manifests/0000_50_cluster-platform-operator-manager_00-rukpak-bundledeployments.crd.yaml, manifests/0000_50_cluster-platform-operator-manager_00-rukpak-bundles.crd.yaml, manifests/0000_50_cluster-platform-operator-manager_01-core-ca.cm.yaml, manifests/0000_50_cluster-platform-operator-manager_01-rukpak-core-admin.sa.yaml, manifests/0000_50_cluster-platform-operator-manager_01-rukpak-webhooks-admin.sa.yaml, manifests/0000_50_cluster-platform-operator-manager_01-serviceaccount.yaml, manifests/0000_50_cluster-platform-operator-manager_01-webhook-ca.cm.yaml, manifests/0000_50_cluster-platform-operator-manager_02-metricsservice.yaml, manifests/0000_50_cluster-platform-operator-manager_02-rukpak-core.service.yaml, manifests/0000_50_cluster-platform-operator-manager_02-rukpak-webhook.service.yaml, manifests/0000_50_cluster-platform-operator-manager_03_rbac.yaml, manifests/0000_50_cluster-platform-operator-manager_04-rukpak-core.deployment.yaml, manifests/0000_50_cluster-platform-operator-manager_04-rukpak-webhooks.deployment.yaml, manifests/0000_50_cluster-platform-operator-manager_05-rukpak.validating-webhook-configuration.yaml, manifests/0000_50_cluster-platform-operator-manager_06-deployment.yaml, manifests/0000_50_cluster-platform-operator-manager_07-aggregated-clusteroperator.yaml
Update the CVO manifests, and update the annotations that are used. Removes the ibm cloud cluster profile for the aggregate CO object, excludes the openshift hosted cluster profile from the annotations, and adds a quote around the "TechPreviewNoUpgrade" feature set.
Moving this out of the #23 PR.
=> config,manifests: Update the annotations used in the CVO manifests

cmd/main.go, config/manager/manager.yaml, controllers/aggregated_clusteroperator_controller.go, internal/clusteroperator/release.go, manifests/0000_50_cluster-platform-operator-manager_06-deployment.yaml, test/e2e/aggregated_clusteroperator_test.go
Ensure the aggregated platform operator CO resource has a populated status.Versions field. By default, the YAML manifest for this resource has a populated status.Version but the aggregate CO controller logic stomps on this value during reconciliation. Update that reconciliation logic to ensure this value is persisted during events.
=> *: Ensure the aggregate CO controller populates the status.Versions field

Makefile
This PR updates our usage of `yq` from V3 to V4 to prevent local runs of `make manifests` from failing.
=> fix: update yq from V3 to v4

Dockerfile, Makefile, manifests/image-references
Introduces platform operators to the OCP payload. The CPOM and rukpak components will only be present when the "TechPreviewNoUpgrades" feature set has been enabled.
See [the [OLM-2668](https://issues.redhat.com//browse/OLM-2668) gist](https://gist.github.com/timflannagan/5490dc7471831da11772cd695512b863) for more information.
=> Introduce platform operators to the OCP payload

controllers/aggregated_clusteroperator_controller.go, internal/clusteroperator/types.go, test/e2e/aggregated_clusteroperator_test.go
Remove the multiple constant variable declarations and any references that hardcode the clusteroperator resource names.
=> *: Remove duplicate constant variables for the ClusterOperator resource names

.gitignore, test/e2e/aggregated_clusteroperator_test.go, test/e2e/collect-ci-artifacts.sh, test/e2e/platform_operators_test.go, test/e2e/util.go
Related to #66 which has the debug information present.
=> Improve the visiblity into individual e2e test case failures

test/e2e/aggregated_clusteroperator_test.go, test/e2e/platform_operators_test.go
When deleting any PlatformOperator or BundleDeployment resources, specify the foreground cascading deletion propagation policy in relevant client usage in the e2e suite.
This should cut down on the number of flakes that result in failed installations due to tests re-using the same PlatformOperator package name. The issue here is we don't give the underlying cascading deletion enough time to fully uninstall before we attempt a new installation. And the result here is that the BundleDeployment installation fails as some resources already exist and cannot be successfully adopted.
=> test/e2e: Use foreground cascading deletion

test/e2e/util.go
Ensure we're preserving the existing environment before running any exec.Commands. I noticed locally when running the e2e suite that the underlying bash script wasn't able to find 'oc' despite that executable being in my $PATH, and the `which oc` was outputting strange results when run in isolation. Explicitly specifying the existing environment via `os.Environ()` which should include the $PATH variable helped fix this pathing issue.
=> test/e2e: Preserve the existing environment when using exec.Command

Makefile, config/default/kustomization.yaml, manifests/0000_50_cluster-platform-operator-manager_00-namespace.yaml, manifests/0000_50_cluster-platform-operator-manager_04-rukpak-core.deployment.yaml, manifests/0000_50_cluster-platform-operator-manager_04-rukpak-webhooks.deployment.yaml, manifests/0000_50_cluster-platform-operator-manager_06-deployment.yaml
Adding annotations to namespace and deployment to support the workload pinning enhancement.
These annotations are used to modify the resources and correctly assign workloads to specific cpu sets when the cluster is configured for CPU partitioning.
https://github.com/openshift/enhancements/pull/703
https://github.com/openshift/enhancements/pull/1213
=> 	OCPBUGS-10333: feat: add workload pinning annotations

Dockerfile
Temporarily remove this image from the release payload. We are moving the rukpak manifests to openshift/cluster-olm-operator and have to do it through a series of PRs. The easiest way to do the move is to stop including platform-operators in the payload, then add it back after the move is done.
=> Temporarily remove from payload

Makefile, manifests/0000_50_cluster-platform-operator-manager_07-aggregated-clusteroperator.yaml
[ClusterOperator is a cluster-scoped resource][1], so there is no point in requesting a `namespace`.
[1]: https://github.com/openshift/api/blob/b8a18fdc040de6208d49111ac776ac08b98e6bb7/config/v1/types_cluster_operator.go#L9
=> OCPBUGS-22457: manifests/0000_50_cluster-platform-operator-manager_07-aggregated-clusteroperator: Drop namespace

Makefile
3dd23a9b68 (#64) removed the final consumer. Subsequently 39662d60ca (#95) removed some other related targets and the `YQ` variable definition.  But this `manifests` prereq snuck through, until this commit, where I'm removing it.
=> Makefile: Drop yq prerequisite from 'manifests' target

Dockerfile
Platform Operators is not currently a priority for the Operator Framework group, and its continued presence and dependence on Rukpak is forcing us to spend time keeping Platform Operators up to date. In order to remain focused on delivering OLMv1, we are removing Platform Operators from OCP. 
It is only enabled under the `TechPreviewNoUpgrade` feature gate, so its removal is not expected to have an impact on production systems.
=> OPRUN-3337: Remove platform-operators from the OCP payload
